#######################################################################################
#@TYPE: Distribution
#@NAME: imdt-qcom-distro-perf
#@DESCRIPTION: IMDT Embedded Linux Distribution
# (glibc based) with performance orientation. Serial console and a few debug features in
# base line distro are disabled. Uses a kernel config targeting faster bootup and performance.
# Allows root user access.
#
# Supported DISTROOVERRIDES are
#  * qti-distro-base
#  * qti-distro-perf
#  * qti-distro-fullstack-perf
#  * qti-distro-rb-perf
#
# For same variable override precedence order is
# qti-distro-rb-perf > qti-distro-fullstack-perf > qti-distro-perf > qti-distro-base
#######################################################################################

# Honor qti-distro-perf override
DISTROOVERRIDES =. "qti-distro-perf:"

require conf/distro/include/qti-distro-fullstack.inc

DISTRO_NAME = "IMDT Linux Embedded distro targeting performance builds."

#Enable IB2C
DISTRO_FEATURES += "qti-ib2c"

#Enable UVC
DISTRO_FEATURES += "qti-uvc"

#Enable vulkan
DISTRO_FEATURES += "vulkan"

# Enable Machine Learning Features
DISTRO_FEATURES += "qti-qnn"
DISTRO_FEATURES += "qti-snpe"
DISTRO_FEATURES += "tensorflow-lite"

# Remove selinux distro feature defined in fullstack distro.
DISTRO_FEATURES:remove = "selinux"

DISTRO_FEATURES:remove = " \
        dm-verity \
        fbdev \
        qti-security \
        qwesd \
"
