#######################################################################################
#@TYPE: Distribution
#@NAME: imdt-qcom-distro-debug
#@DESCRIPTION: IMDT Embedded Linux Distribution
# (glibc based) having debugging capabilities. Not optimized for performance.
# Allows root user access.
#
# Supported DISTROOVERRIDES are
#  * qti-distro-base
#  * qti-distro-debug
#  * qti-distro-fullstack-debug
#  * qti-distro-rb-debug
#
# For same variable override precedence order is
# qti-distro-rb-debug > qti-distro-fullstack-debug > qti-distro-debug > qti-distro-base
#######################################################################################

# Honor qti-distro-debug override
DISTROOVERRIDES =. "qti-distro-debug:"

require conf/distro/include/qti-distro-fullstack.inc

DISTRO_NAME = "IMDT Linux Embedded distro targeting debug builds."

#Enable IB2C
DISTRO_FEATURES += "qti-ib2c"

#Enable UVC
DISTRO_FEATURES += "qti-uvc"

#Enable vulkan
DISTRO_FEATURES += "vulkan"

# Enable Machine Learning Features
DISTRO_FEATURES += "qti-qnn"
DISTRO_FEATURES += "qti-snpe"
DISTRO_FEATURES += "tensorflow-lite"

# Remove selinux distro feature defined in fullstack distro.
DISTRO_FEATURES:remove = "selinux"

DISTRO_FEATURES:remove = " \
        dm-verity \
        fbdev \
        qti-security \
        qwesd \
"

# Set DEBUG_BUILD to use flags from DEBUG_OPTIMIZATION variable
DEBUG_BUILD = "1"

# Bring in debug utilities.
DISTRO_EXTRA_RDEPENDS += "packagegroup-qti-debug-tools"

#enable systemd journal
SYSTEMD_ENABLE_JOURNAL = "1"
