#!/bin/bash
# Autogenerated by IMDT
patch -p1 -d ${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/src/kernel-5.15/kernel_platform/msm-kernel -i ${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/poky/meta-imdt-qcom/patches/msm-kernel/files/0001-Add-support-for-booting-IMDT-SOM8550-in-Linux-7.patch
patch -p1 -d ${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/src/kernel-5.15/kernel_platform/qcom/proprietary/devicetree -i ${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/poky/meta-imdt-qcom/patches/msm-kernel-devicetree/files/0001-Initial-board-bringup-of-IMDT-SBC8550-14.patch
patch -p1 -d ${QCOM_ROOT_DIR}/aop_proc -i ${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/poky/meta-imdt-qcom/patches/aop-proc/files/0001-Configure-PMIC-s-L5B-and-L15B-2.patch
patch -p1 -d ${QCOM_ROOT_DIR}/adsp_proc -i ${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/poky/meta-imdt-qcom/patches/adsp-proc/files/0001-Disable-charger-PMIC-in-ADSP-1.patch
patch -p1 -d ${QCOM_ROOT_DIR}/boot_images -i ${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/poky/meta-imdt-qcom/patches/boot-images/files/0001-Add-support-for-booting-the-IMDT-SOM8550-3.patch
cp ${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/poky/meta-imdt-qcom/contents.xml ${QCOM_ROOT_DIR}
